package cn.easyreport.sync.datasync;

import cn.easyreport.sync.mapper.ErDataTransferMapper;
import cn.easyreport.sync.mapper.ErDataTransferLogMapper;
import cn.easyreport.sync.mapper.ErDataTransferProgressMapper;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * Oracle数据同步执行器
 */
public class OracleDataSyncExecutor extends DataSyncExecutor {

    /** 记录本次批量插入前被改为 BY DEFAULT 的 ALWAYS 身份列，用于插入后还原 */
    private final List<String> alteredAlwaysColumns = new ArrayList<>();

    public OracleDataSyncExecutor(ErDataTransferMapper transferMapper,
                                  ErDataTransferLogMapper logMapper,
                                  ErDataTransferProgressMapper progressMapper) {
        super(transferMapper, logMapper, progressMapper, new OracleDataSyncValueConverter());
    }

    /**
     * 插入前：将目标表中所有 GENERATED ALWAYS AS IDENTITY 列临时改为
     * GENERATED BY DEFAULT AS IDENTITY，以允许插入显式值。
     * tableName 格式："SCHEMA"."TABLE"
     */
    @Override
    protected void beforeBatchInsert(Connection targetConn, String tableName) throws Exception {
        alteredAlwaysColumns.clear();
        String[] parts = parseOracleTableName(tableName);
        if (parts == null) return;
        String owner = parts[0];
        String table = parts[1];

        String querySql = "SELECT column_name FROM all_tab_identity_cols" +
                          " WHERE owner = '" + owner.replace("'", "''") + "'" +
                          " AND table_name = '" + table.replace("'", "''") + "'" +
                          " AND generation_type = 'ALWAYS'";
        // 先收集所有 ALWAYS 列名，关闭 ResultSet 后再执行 ALTER（避免同一 Statement 重入关闭 RS）
        List<String> alwaysCols = new ArrayList<>();
        try (Statement st = targetConn.createStatement();
             ResultSet rs = st.executeQuery(querySql)) {
            while (rs.next()) {
                alwaysCols.add(rs.getString(1));
            }
        }
        try (Statement st = targetConn.createStatement()) {
            for (String col : alwaysCols) {
                String alterSql = "ALTER TABLE " + tableName +
                                  " MODIFY \"" + col + "\" GENERATED BY DEFAULT AS IDENTITY";
                st.execute(alterSql);
                alteredAlwaysColumns.add(col);
                System.out.println("[OracleDataSyncExecutor] 临时改为 BY DEFAULT: " + tableName + "." + col);
            }
        }
    }

    /**
     * 插入后（无论成功与否）：将之前改过的列还原为 GENERATED ALWAYS AS IDENTITY。
     */
    @Override
    protected void afterBatchInsert(Connection targetConn, String tableName) throws Exception {
        if (alteredAlwaysColumns.isEmpty()) return;
        try (Statement st = targetConn.createStatement()) {
            for (String col : alteredAlwaysColumns) {
                try {
                    String alterSql = "ALTER TABLE " + tableName +
                                      " MODIFY \"" + col + "\" GENERATED ALWAYS AS IDENTITY";
                    st.execute(alterSql);
                    System.out.println("[OracleDataSyncExecutor] 还原为 ALWAYS: " + tableName + "." + col);
                } catch (Exception e) {
                    System.err.println("[OracleDataSyncExecutor] 还原 ALWAYS 失败（忽略）: " + e.getMessage());
                }
            }
        } finally {
            alteredAlwaysColumns.clear();
        }
    }

    /**
     * 解析 Oracle 表名 "SCHEMA"."TABLE"，返回 [schema, table]（不含引号，已大写）。
     * 返回 null 表示无法解析。
     */
    private String[] parseOracleTableName(String tableName) {
        if (tableName == null) return null;
        // 格式："SCHEMA"."TABLE"
        int dot = tableName.indexOf("\".");
        if (dot < 0) return null;
        String schema = tableName.substring(1, dot);           // 去掉首尾引号
        String table = tableName.substring(dot + 3, tableName.length() - 1); // 去掉 "." 前缀和末尾引号
        return new String[]{schema.toUpperCase(), table.toUpperCase()};
    }

    /**
     * 数据同步前自动将目标 Oracle 表的 CHAR(n)/VARCHAR2(n) 列升级为 NCHAR(n)/NVARCHAR2(n)，
     * 避免写入多字节 Unicode 字符（如中文）时触发 ORA-12899。
     */
    @Override
    protected void prepareTargetSchema(Connection sourceConn, Connection targetConn,
                                       String sourceSchema, String sourceTable,
                                       String targetTableName) throws Exception {
        String[] parts = parseOracleTableName(targetTableName);
        if (parts == null) return;
        String owner = parts[0];
        String table = parts[1];

        // 查询目标表中所有 CHAR/VARCHAR2 列（字节语义，即 CHAR_USED = 'B'）
        String querySql = "SELECT column_name, data_type, char_length FROM all_tab_columns" +
                          " WHERE owner = '" + owner.replace("'", "''") + "'" +
                          " AND table_name = '" + table.replace("'", "''") + "'" +
                          " AND data_type IN ('CHAR', 'VARCHAR2')" +
                          " AND char_used = 'B'";

        List<String> alterSqls = new ArrayList<>();
        try (Statement st = targetConn.createStatement();
             ResultSet rs = st.executeQuery(querySql)) {
            while (rs.next()) {
                String colName  = rs.getString("column_name");
                String dataType = rs.getString("data_type");
                int    charLen  = rs.getInt("char_length");
                String newType;
                if ("CHAR".equals(dataType)) {
                    newType = "NCHAR(" + charLen + ")";
                } else {
                    // VARCHAR2: Oracle NVARCHAR2 最大 4000
                    newType = charLen > 4000 ? "NCLOB" : "NVARCHAR2(" + charLen + ")";
                }
                alterSqls.add("ALTER TABLE " + targetTableName +
                               " MODIFY \"" + colName + "\" " + newType);
            }
        }

        if (!alterSqls.isEmpty()) {
            try (Statement st = targetConn.createStatement()) {
                for (String sql : alterSqls) {
                    System.out.println("[OracleDataSyncExecutor] 升级列类型: " + sql);
                    st.execute(sql);
                }
            }
            targetConn.commit();
        }
    }

    @Override
    protected void clearTable(Connection conn, String tableName) throws Exception {
        // Oracle 使用 TRUNCATE TABLE 清空表
        // tableName 可能已经是完全限定名格式: "SCHEMA"."TABLE"
        try (Statement st = conn.createStatement()) {
            String sql = tableName.contains("\"")
                ? "TRUNCATE TABLE " + tableName
                : "TRUNCATE TABLE \"" + tableName + "\"";
            st.execute(sql);
        }
    }

    /**
     * Oracle JDBC 对 MERGE INTO 使用 addBatch/executeBatch 会静默失败，
     * 改为逐行 executeUpdate，提交仍按批次。
     */
    @Override
    protected boolean useRowByRowUpsert() {
        return true;
    }

    /**
     * Oracle INSERT ALL SQL 文本增长较快，保守限制单条语句行数。
     */
    @Override
    protected int getMaxFullInsertRows() {
        return 500;
    }

    /**
     * Oracle 不支持普通 INSERT INTO ... VALUES (...), (...) 多行写法。
     */
    @Override
    protected void executeFullInsertStatement(Connection conn, List<Object[]> rows, int start, int end,
                                              String targetTable, List<String> cols) throws Exception {
        String colPart = buildTargetColumnList(cols);
        String rowTemplate = buildPlaceholderRow(cols.size());
        String tableName = normalizeTargetTableSqlName(targetTable);

        StringBuilder sql = new StringBuilder("INSERT ALL ");
        for (int i = start; i < end; i++) {
            sql.append("INTO ").append(tableName).append(" ").append(colPart)
                    .append(" VALUES ").append(rowTemplate).append(" ");
        }
        sql.append("SELECT 1 FROM DUAL");

        try (PreparedStatement ps = conn.prepareStatement(sql.toString())) {
            bindRows(ps, rows, start, end);
            ps.executeUpdate();
        }
    }

    /**
     * Oracle 不支持 LIMIT，使用 FETCH FIRST n ROWS ONLY 语法
     */
    @Override
    protected String buildAlignDeleteSelectSql(String targetTable, String pk, String tsField) {
        return "SELECT " + quoteTargetIdentifier(pk) + ", " + quoteTargetIdentifier(tsField) +
               " FROM " + targetTable +
               " WHERE " + quoteTargetIdentifier(tsField) + " >= ? ORDER BY " + quoteTargetIdentifier(tsField) +
               ", " + quoteTargetIdentifier(pk) + " FETCH FIRST ? ROWS ONLY";
    }

    /**
     * Oracle keyset 分页，FETCH FIRST 参数在末尾（参数顺序与基类一致：ts, ts, pk, batchSize）
     */
    @Override
    protected String buildAlignDeleteSelectSqlAfter(String targetTable, String pk, String tsField) {
        return "SELECT " + quoteTargetIdentifier(pk) + ", " + quoteTargetIdentifier(tsField) +
               " FROM " + targetTable +
               " WHERE (" + quoteTargetIdentifier(tsField) + " > ?" +
               " OR (" + quoteTargetIdentifier(tsField) + " = ? AND " + quoteTargetIdentifier(pk) + " > ?))" +
               " ORDER BY " + quoteTargetIdentifier(tsField) + ", " + quoteTargetIdentifier(pk) +
               " FETCH FIRST ? ROWS ONLY";
    }

    @Override
    protected String qualify(String schema, String table) {
        if (schema == null || schema.isEmpty()) {
            return table;
        }
        // Oracle: "SCHEMA"."TABLE"（大写）
        return "\"" + schema.toUpperCase() + "\".\"" + table.toUpperCase() + "\"";
    }
}
